"""
Database Models, Schemas, and Utilities
"""

from .models import (
    Base,
    DemoSession,
    DemoAction,
    CustomerQuestion,
    DemoScript,
    DemoAnalytics,
    DemoStatus,
    ActionType,
    QuestionIntent,
    Sentiment,
    DemoSessionCreate,
    DemoSessionResponse,
    DemoActionCreate,
    DemoActionResponse,
    CustomerQuestionCreate,
    CustomerQuestionResponse,
    DemoScriptCreate,
    DemoScriptResponse,
    DemoAnalyticsResponse,
    DemoMetrics,
)

from .connection import (
    engine,
    SessionLocal,
    init_db,
    get_db,
    get_db_session,
    check_db_connection,
    close_db_connection,
)

from .crud import (
    create_demo_session,
    get_demo_session,
    update_demo_session,
    start_demo_session,
    complete_demo_session,
    abandon_demo_session,
    get_active_sessions,
    get_sessions_by_customer,
    create_demo_action,
    start_demo_action,
    complete_demo_action,
    get_session_actions,
    create_customer_question,
    answer_customer_question,
    get_session_questions,
    get_demo_script,
    get_all_demo_scripts,
    create_daily_analytics,
    update_daily_analytics,
    get_analytics_range,
    get_dashboard_stats,
    delete_old_sessions,
)

__all__ = [
    # Models
    "Base",
    "DemoSession",
    "DemoAction",
    "CustomerQuestion",
    "DemoScript",
    "DemoAnalytics",
    # Enums
    "DemoStatus",
    "ActionType",
    "QuestionIntent",
    "Sentiment",
    # Schemas
    "DemoSessionCreate",
    "DemoSessionResponse",
    "DemoActionCreate",
    "DemoActionResponse",
    "CustomerQuestionCreate",
    "CustomerQuestionResponse",
    "DemoScriptCreate",
    "DemoScriptResponse",
    "DemoAnalyticsResponse",
    "DemoMetrics",
    # Connection
    "engine",
    "SessionLocal",
    "init_db",
    "get_db",
    "get_db_session",
    "check_db_connection",
    "close_db_connection",
    # CRUD
    "create_demo_session",
    "get_demo_session",
    "update_demo_session",
    "start_demo_session",
    "complete_demo_session",
    "abandon_demo_session",
    "get_active_sessions",
    "get_sessions_by_customer",
    "create_demo_action",
    "start_demo_action",
    "complete_demo_action",
    "get_session_actions",
    "create_customer_question",
    "answer_customer_question",
    "get_session_questions",
    "get_demo_script",
    "get_all_demo_scripts",
    "create_daily_analytics",
    "update_daily_analytics",
    "get_analytics_range",
    "get_dashboard_stats",
    "delete_old_sessions",
]
